codecov:
  require_ci_to_pass: yes
  
coverage:
  precision: 2
  round: down
  range: "70...100"
  
  ignore:
    - "src/tests/**/*"
    
  status:
    project:
      default:
        target: auto
        threshold: 1%
        # Specify what coverage types to track
        coverage_threshold:
          line: 80
          branch: 90
    patch:
      default:
        target: auto
        threshold: 1%

comment:
  layout: "reach,diff,flags,tree"
  behavior: default